# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



Team.create(team: "Atalanta", flag: "https://cdn.staticneo.com/w/pes/c/c2/Atalanta.png", founded: "1907", moment_title: "", moments: "")
Team.create(team: "Benevento", flag: "https://pbs.twimg.com/profile_images/651792426223452160/FQqhQs1M_400x400.png", founded: "1929", moment_title: "", moments: "")
Team.create(team: "Bologna", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/189.png", founded: "1909", moment_title: "", moments: "")
Team.create(team: "Cagliari", flag: "http://futhead.cursecdn.com/static/img/15/clubs_large/1842.png", founded: "1920", moment_title: "", moments: "")
Team.create(team: "Chievo Verona", flag: "Chievo-Verona.ico", founded: "1903", moment_title: "", moments: "")
Team.create(team: "Crotone", flag: "http://futhead.cursecdn.com/static/img/17/clubs/110734.png", founded: "1910", moment_title: "", moments: "")
Team.create(team: "Fiorentina", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/110374.png", founded: "1926", moment_title: "", moments: "")
Team.create(team: "Genoa", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/110556.png", founded: "1893", moment_title: "", moments: "")
Team.create(team: "Hellas Verona", flag: "Hellas-Verona.ico", founded: "1929", moment_title: "", moments: "")
Team.create(team: "Inter Milan", flag: "http://icons.iconarchive.com/icons/giannis-zographos/italian-football-club/256/Internazionale-icon.png", founded: "1908", moment_title: "", moments: "")
Team.create(team: "Juventus", flag: "https://www.toralarm.com/api/proxy/images/ta/images/teams/9245/256/", founded: "1897", moment_title: "", moments: "")
Team.create(team: "Lazio", flag: "http://futhead.cursecdn.com/static/img/14/clubs/46.png", founded: "1900", moment_title: "", moments: "")
Team.create(team: "AC Milan", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410467610_fc-ac-milan.png", founded: "1899", moment_title: "", moments: "")
Team.create(team: "Napoli", flag: "http://futhead.cursecdn.com/static/img/17/items/badges/6000083.png", founded: "1926", moment_title: "", moments: "")
Team.create(team: "Roma", flag: "https://i.pinimg.com/originals/e8/bf/ff/e8bfff76e56d0a7e49f2418cc6c77e0e.jpg", founded: "1927", moment_title: "", moments: "")
Team.create(team: "Sampdoria", flag: "http://icons.iconarchive.com/icons/giannis-zographos/italian-football-club/256/Sampdoria-icon.png", founded: "1946", moment_title: "", moments: "")
Team.create(team: "Sassuolo", flag: "http://futhead.cursecdn.com/static/img/15/clubs_large/111974.png", founded: "1920", moment_title: "", moments: "")
Team.create(team: "SPAL", flag: "https://toralarm.com/api/proxy/images/ta/images/teams/9774160/256/", founded: "1907", moment_title: "", moments: "")
Team.create(team: "Torino", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/54.png", founded: "1906", moment_title: "", moments: "")
Team.create(team: "Udinese", flag: "http://football-craze.com/wp-content/uploads/2011/04/Udinese-icon.png", founded: "1896", moment_title: "", moments: "")
Team.create(team: "Arsenal", flag: "http://futhead.cursecdn.com/static/img/17/items/badges/6000074.png", founded: "1886", moment_title: "", moments: "")
Team.create(team: "Bournemouth", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/1943.png", founded: "1899", moment_title: "", moments: "")
Team.create(team: "Brighton & Hove Albion", flag: "http://soccerlogo.net/uploads/posts/2015-02/1424204174_fc-brighton-hove-albion.png", founded: "1904", moment_title: "", moments: "")
Team.create(team: "Burnley", flag: "http://futhead.cursecdn.com/static/img/15/clubs_large/1796.png", founded: "1882", moment_title: "", moments: "")
Team.create(team: "Chelsea", flag: "https://cdn.images.express.co.uk/img/dynamic/footballteams/x256/17.png", founded: "1905", moment_title: "", moments: "")
Team.create(team: "Crystal Palace", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/1799.png", founded: "1905", moment_title: "", moments: "")
Team.create(team: "Everton", flag: "https://i.pinimg.com/originals/7e/e0/2d/7ee02d8fba229a9c3fe16dac807b5223.png", founded: "1878", moment_title: "", moments: "")
Team.create(team: "Huddersfield Town", flag: "http://soccerlogo.net/uploads/posts/2015-02/1424201155_fc-huddersfield-town.png", founded: "1908", moment_title: "", moments: "")
Team.create(team: "Leicster City", flag: "http://futhead.cursecdn.com/static/img/17/items/badges/6000102.png", founded: "1884", moment_title: "", moments: "")
Team.create(team: "Liverpool", flag: "http://futhead.cursecdn.com/static/img/17/items/badges/6000079.png", founded: "1892", moment_title: "", moments: "")
Team.create(team: "Manchester City", flag: "http://images-1.smartsave.com/images/attractions/1162/NEW-LOGO-256x256.png", founded: "1880", moment_title: "", moments: "")
Team.create(team: "Manchester United", flag: "Manchester-United.ico", founded: "1878", moment_title: "", moments: "")
Team.create(team: "Newcastle United", flag: "https://i.pinimg.com/474x/c9/c8/26/c9c826b3dee7180ae26fbc2e1ae3f34e--soccer-tips-say-anything.jpg", founded: "1892", moment_title: "", moments: "")
Team.create(team: "Southampton", flag: "http://icons.iconarchive.com/icons/giannis-zographos/english-football-club/256/Southampton-FC-icon.png", founded: "1885", moment_title: "", moments: "")
Team.create(team: "Stoke City", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410463802_fc-stoke_city.png", founded: "1863", moment_title: "", moments: "")
Team.create(team: "Swansea City", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410462864_fc-swansea_city.png", founded: "1912", moment_title: "", moments: "")
Team.create(team: "Tottenham Hotspur", flag: "https://i.pinimg.com/originals/77/56/78/775678aa3f6ff160b7335fd82dd04d94.jpg", founded: "1882", moment_title: "", moments: "")
Team.create(team: "Watford", flag: "http://icons.iconarchive.com/icons/giannis-zographos/english-football-club/256/Watford-FC-icon.png", founded: "1881", moment_title: "", moments: "")
Team.create(team: "West Bromwich Albion", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410464253_fc-west-bromwich-albion.png", founded: "1878", moment_title: "", moments: "")
Team.create(team: "West Ham United", flag: "West-Ham-United.ico", founded: "1895", moment_title: "", moments: "")
Team.create(team: "Amiens", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/France/SC-Amiens.png", founded: "1901", moment_title: "", moments: "")
Team.create(team: "Angers", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/1530.png", founded: "1919", moment_title: "", moments: "")
Team.create(team: "Bordeaux", flag: "http://futhead.cursecdn.com/static/img/15/clubs_large/59.png", founded: "1881", moment_title: "", moments: "")
Team.create(team: "Caen", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/210.png", founded: "1913", moment_title: "", moments: "")
Team.create(team: "Dijon FCO", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/France/Dijon-FCO.png", founded: "1998", moment_title: "", moments: "")
Team.create(team: "Guingamp", flag: "http://futhead.cursecdn.com/static/img/16/clubs/62.png", founded: "1912", moment_title: "", moments: "")
Team.create(team: "Lille", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/65.png", founded: "1944", moment_title: "", moments: "")
Team.create(team: "Lyon", flag: "https://pbs.twimg.com/profile_images/378800000015716644/8530133290d923e3ee554271682dcf99.png", founded: "1950", moment_title: "", moments: "")
Team.create(team: "Marseille", flag: "https://pespespes.files.wordpress.com/2013/08/olympique-de-marseille.png", founded: "1899", moment_title: "", moments: "")
Team.create(team: "FC Metz", flag: "http://www.futwiz.com/assets/img/fifa16/badges/68.png", founded: "1932", moment_title: "", moments: "")
Team.create(team: "AC Monaco", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/69.png", founded: "1924", moment_title: "", moments: "")
Team.create(team: "Montpellier", flag: "http://www.zlatanibrahimovic.com/images/icons_clubs/montpellier/montpellier-logo-256.png", founded: "1974", moment_title: "", moments: "")
Team.create(team: "FC Nantes", flag: "http://futhead.cursecdn.com/static/img/15/clubs_large/71.png", founded: "1943", moment_title: "", moments: "")
Team.create(team: "OGC Nice", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/72.png", founded: "1904", moment_title: "", moments: "")
Team.create(team: "Paris San-Germain FC", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/France/Paris-Saint-Germain-FC.png", founded: "1970", moment_title: "", moments: "")
Team.create(team: "Stade Rennes", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/74.png", founded: "1901", moment_title: "", moments: "")
Team.create(team: "Saint-Etienne", flag: "http://icons.iconarchive.com/icons/giannis-zographos/french-football-club/256/AS-Saint-Etienne-icon.png", founded: "1909", moment_title: "", moments: "")
Team.create(team: "Racing Strasbourg", flag: "http://soccerlogo.net/uploads/posts/2016-05/1464450034_rc-strasbourg-alsace.png", founded: "1906", moment_title: "", moments: "")
Team.create(team: "Toulouse", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413539626_fc-toulouse.png", founded: "1970", moment_title: "", moments: "")
Team.create(team: "Troyes", flag: "http://futhead.cursecdn.com/static/img/17/clubs/294.png", founded: "1986", moment_title: "", moments: "")
Team.create(team: "FC Augsburg", flag: "https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAAQEAAAAJDc3MWVjNzEzLWQwNjMtNDdiZi1hMGVmLTQ1ZGNmMGRhOGU1Mg.png", founded: "1907", moment_title: "", moments: "")
Team.create(team: "Bayer 04 Leverkusen", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/Germany/Bayer-04-Leverkusen.png", founded: "1904", moment_title: "", moments: "")
Team.create(team: "Bayern Munich", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/21.png", founded: "1900", moment_title: "", moments: "")
Team.create(team: "Borussia Dortmund", flag: "https://pesgalaxy.com/index.php/Attachment/9722-Borussia-Dortmund-png/", founded: "1909", moment_title: "", moments: "")
Team.create(team: "Borussia Monchengladbach", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410888653_fc-borussia-monchengladbach-256.png", founded: "1900", moment_title: "", moments: "")
Team.create(team: "Eintracht Frankfurt", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413537689_fc-eintracht-frankfurt.png", founded: "1899", moment_title: "", moments: "")
Team.create(team: "SC Freiburg", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413536653_fc-freiburg.png", founded: "1904", moment_title: "", moments: "")
Team.create(team: "Hamburg SV", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413538097_fc-hamburger-sv.png", founded: "1919", moment_title: "", moments: "")
Team.create(team: "Hannover 96", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413537893_fc-hannover-96.png", founded: "1896", moment_title: "", moments: "")
Team.create(team: "Hertha Berlin SC", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/166.png", founded: "1892", moment_title: "", moments: "")
Team.create(team: "TSG Hoffenheim", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413537050_fc-hoffenheim.png", founded: "1899", moment_title: "", moments: "")
Team.create(team: "FC Koln", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/Germany/1.-FC-Koln.png", founded: "1948", moment_title: "", moments: "")
Team.create(team: "RB Leipzig", flag: "https://pesgalaxy.com/index.php/Attachment/9733-RB-Leipzig-PNG/", founded: "2009", moment_title: "", moments: "")
Team.create(team: "FSV Mainz", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413536846_fc-mainz-05.png", founded: "1905", moment_title: "", moments: "")
Team.create(team: "Schalke 04", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410887128_fc-schalke-04-256.png", founded: "1904", moment_title: "", moments: "")
Team.create(team: "VfB Stuttgart", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/Germany/VfB-Stuttgart.png", founded: "1893", moment_title: "", moments: "")
Team.create(team: "Werder Bremen", flag: "http://soccerlogo.net/uploads/posts/2014-10/1413536147_fc-werder-bremen.png", founded: "1899", moment_title: "", moments: "")
Team.create(team: "VfL Wolfsburg", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410891791_fc-wolfsburg-256.png", founded: "1945", moment_title: "", moments: "")
Team.create(team: "Alaves", flag: "http://soccerlogo.net/uploads/posts/2016-05/1463755340_deportivo-alavgs.png", founded: "1921", moment_title: "", moments: "")
Team.create(team: "Athletic Bibao", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/448.png", founded: "1898", moment_title: "", moments: "")
Team.create(team: "Atletico Madrid", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/Spain/Club-Atletico-de-Madrid.png", founded: "1903", moment_title: "", moments: "")
Team.create(team: "FC Barcelona", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/241.png", founded: "1899", moment_title: "", moments: "")
Team.create(team: "Real Betis", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/449.png", founded: "1907", moment_title: "", moments: "")
Team.create(team: "Celta Vigo", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410852957_fc-celta-vigo-256.png", founded: "1923", moment_title: "", moments: "")
Team.create(team: "Deportivo de La Coruna", flag: "http://pesstatsdatabase.com/PSD/PSD/Images/Clubs/Spain/RC-Deportivo-La-Coruna.png", founded: "1906", moment_title: "", moments: "")
Team.create(team: "Eibar FC", flag: "https://upload.wikimedia.org/wikipedia/en/f/ff/SD_Eibar_logo_2016.png", founded: "1940", moment_title: "", moments: "")
Team.create(team: "RCD Espanyol", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410854906_fc-espanyol-256.png", founded: "1900", moment_title: "", moments: "")
Team.create(team: "Getafe CF", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410855482_fc-getafe-256.png", founded: "1983", moment_title: "", moments: "")
Team.create(team: "Girona", flag: "http://soccerlogo.net/uploads/posts/2016-05/1463754346_girona-fc.png", founded: "1930", moment_title: "", moments: "")
Team.create(team: "Las Palmas", flag: "http://icons.iconarchive.com/icons/giannis-zographos/spanish-football-club/256/UD-Las-Palmas-icon.png", founded: "1949", moment_title: "", moments: "")
Team.create(team: "Leganes", flag: "http://soccerlogo.net/uploads/posts/2016-05/1463754957_cd-legangs.png", founded: "1928", moment_title: "", moments: "")
Team.create(team: "Levante", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410535424_fc-levante-256.png", founded: "1909", moment_title: "", moments: "")
Team.create(team: "Malaga", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410535010_fc-malaga-256.png", founded: "1904", moment_title: "", moments: "")
Team.create(team: "Real Madrid", flag: "http://futhead.cursecdn.com/static/img/17/clubs_large/243.png", founded: "1902", moment_title: "", moments: "")
Team.create(team: "Real Sociedad", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410853437_fc-real-sociedad-256.png", founded: "1909", moment_title: "", moments: "")
Team.create(team: "Sevilla", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410855169_fc-sevilla-256.png", founded: "1890", moment_title: "", moments: "")
Team.create(team: "Valencia", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410854553_fc-valencia-256.png", founded: "1919", moment_title: "", moments: "")
Team.create(team: "Villarreal", flag: "http://soccerlogo.net/uploads/posts/2014-09/1410856827_fc-villarreal-256.png", founded: "1923", moment_title: "", moments: "")


